# Step 1: Build WAR using Maven
FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Step 2: Deploy WAR to Tomcat
FROM tomcat:10.1.48-jdk17
WORKDIR /usr/local/tomcat/webapps
COPY --from=builder /app/target/LoginWebApp.war ./LoginWebApp.war

# Optional: Environment variables for DB connection
ENV DB_HOST=database-1.cevyoqyq8e62.us-east-1.rds.amazonaws.com
ENV DB_USER=admin
ENV DB_PASS=admin12345

EXPOSE 8080
CMD ["catalina.sh", "run"]